{"uuid": "cabfaca7-c800-47f9-aafb-a84dec469673", "children": ["d62f36a7-ecdf-4c43-83ab-eb6b2227b6d9", "8cbe9ef4-e318-452d-bc6f-3449eb88ca05", "560581a7-651e-4ca8-91fd-dac151265813", "6c0477a3-5f2c-49b9-975b-9e2cd2f8e042", "fda4a6df-e544-4d7e-a5a3-3be852b7f46c", "ab16a92e-1536-49a2-80a4-6cef0eee2ca6"], "befores": [{"name": "start_wiremock", "status": "broken", "statusDetails": {"message": "OSError: [Errno 8] Exec format error: 'docker-compose'\n", "trace": "  File \"/root/.cache/pypoetry/virtualenvs/pytestify-9TtSrW0h-py3.12/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/root/.cache/pypoetry/virtualenvs/pytestify-9TtSrW0h-py3.12/lib/python3.12/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/root/.cache/pypoetry/virtualenvs/pytestify-9TtSrW0h-py3.12/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/.cache/pypoetry/virtualenvs/pytestify-9TtSrW0h-py3.12/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1139, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/.cache/pypoetry/virtualenvs/pytestify-9TtSrW0h-py3.12/lib/python3.12/site-packages/_pytest/fixtures.py\", line 890, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/Users/ja/IdeaProjects/PyTestify/src/pytestify/tests/conftest.py\", line 47, in start_wiremock\n  File \"/usr/local/lib/python3.12/subprocess.py\", line 548, in run\n    with Popen(*popenargs, **kwargs) as process:\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/subprocess.py\", line 1026, in __init__\n    self._execute_child(args, executable, preexec_fn, close_fds,\n  File \"/usr/local/lib/python3.12/subprocess.py\", line 1955, in _execute_child\n    raise child_exception_type(errno_num, err_msg, err_filename)\n"}, "start": 1725190527286, "stop": 1725190527286}], "start": 1725190527286, "stop": 1725190527986}