[32mINFO    [0m pytestify.client.api_client:api_client.py:30 Initialized APIClient with base URL: https://jsonplaceholder.typicode.com
[35mDEBUG   [0m pytestify.client.api_client:api_client.py:50 Created URL: https://jsonplaceholder.typicode.com/posts/1
[32mINFO    [0m pytestify.client.api_client:api_client.py:63 Performing GET request to https://jsonplaceholder.typicode.com/posts/1 with params: None
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1051 Starting new HTTPS connection (1): jsonplaceholder.typicode.com:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:546 https://jsonplaceholder.typicode.com:443 "GET /posts/1 HTTP/11" 200 None
[32mINFO    [0m pytestify.client.api_client:api_client.py:69 GET request to https://jsonplaceholder.typicode.com/posts/1 returned status code 200
[32mINFO    [0m root:test_api_client.py:13 Response of the GET request: <Response [200]>
[32mINFO    [0m root:test_api_client.py:14 Response code: 200
[32mINFO    [0m root:test_api_client.py:17 Response code 200 is matched
[32mINFO    [0m root:test_api_client.py:20 Response received from the GET request is: {'userId': 1, 'id': 1, 'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}
[32mINFO    [0m pytestify.client.api_client:api_client.py:141 Closed APIClient session